name: CI Ubuntu 22.04

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check-ubuntu.yml
    with:
      ubuntu: '22.04'
      source: repository
